import 'package:final_projects/features/onboarding/onboarding.dart';

abstract class AppAssets {
  static const String basePath = 'assets/utils/';
  static const String onboardingpath1 = '${AppAssets.basePath}shop_1.svg';
  static const String cart = '${AppAssets.basePath}cart.svg';
  static const String location = '${AppAssets.basePath}location.svg';
  static const String loc = '${AppAssets.basePath}loc1.svg';
  static const String girle = '${AppAssets.basePath}girle.png';
  static const String man = '${AppAssets.basePath}man.png';
  static const String onboardingpath2 = '${AppAssets.basePath}shop_2.svg';
  static const String onboardingpath3 = '${AppAssets.basePath}shop_3.svg';
  static const String arrow_back = '${AppAssets.basePath}arrow_back.svg';
  static const String email_icon = '${AppAssets.basePath}email_icon.svg';
  static const String user = '${AppAssets.basePath}User.svg';
  static const String call = '${AppAssets.basePath}call.svg';
  static const String stylbar = '${AppAssets.basePath}stylich.svg';
  static const String search = '${AppAssets.basePath}search.svg';
  static const String password_icon = '${AppAssets.basePath}password_icon.svg';
  static const String women = '${AppAssets.basePath}women.png';
  static const String fashion = '${AppAssets.basePath}fashion.png';
  static const String beauty = '${AppAssets.basePath}beauty.png';
  static const String kids = '${AppAssets.basePath}kids.png';
  static const String men = '${AppAssets.basePath}mens.png';
  static const String offer = '${AppAssets.basePath}offer.png';
  static const String product = '${AppAssets.basePath}product.svg';
  static const String product1 = '${AppAssets.basePath}product_1.png';
  static const String star = '${AppAssets.basePath}star.svg';
  static const String star1 = '${AppAssets.basePath}star_1.svg';
  static const String offer1 = '${AppAssets.basePath}offer1.svg';
  static const String profile = '${AppAssets.basePath}profile.png';
  static const String profileicon = '${AppAssets.basePath}ProfileIcon.svg';
  static const String arrow_next = '${AppAssets.basePath}arrow_next.svg';
  static const String heart = '${AppAssets.basePath}Heart.svg';
  static const String logout = '${AppAssets.basePath}Logout.svg';
  static const String setting = '${AppAssets.basePath}Setting.svg';
  static const String bag = '${AppAssets.basePath}Bag.svg';
  static const String bag2 = '${AppAssets.basePath}Bag_2.svg';
  static const String map = '${AppAssets.basePath}map.svg';
  static const String truee = '${AppAssets.basePath}true.svg';
  static const String falsee = '${AppAssets.basePath}false.svg';
  static const String order = '${AppAssets.basePath}no_order.svg';
  static const String getStarted = '${AppAssets.basePath}get_started.png';
}
